# Generated by Django 5.0.6 on 2024-10-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_muhbir'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_muhbir',
            field=models.BooleanField(default=False),
        ),
    ]
