# Generated by Django 5.0.6 on 2024-10-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_client_is_muhbir'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_muhbir', models.BooleanField(default=False)),
                ('daily_limit', models.IntegerField(default=20)),
            ],
        ),
        migrations.AddConstraint(
            model_name='usagelimit',
            constraint=models.UniqueConstraint(fields=('is_muhbir',), name='unique_usage_limit_for_client_type'),
        ),
    ]
