# Generated by Django 5.0.6 on 2024-10-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usagelimit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
