# Generated by Django 5.0.6 on 2024-10-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_category_aidata_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='token_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apikey',
            name='tokens_used',
            field=models.IntegerField(default=0),
        ),
    ]
