# Generated by Django 5.0.6 on 2024-10-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_apikey_token_limit_apikey_tokens_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_refreshed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usagelimit',
            name='history_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
