# Generated by Django 5.0.2 on 2024-10-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_conversation_last_refreshed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='request_count',
            field=models.PositiveBigIntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='apikey',
            name='request_used',
            field=models.IntegerField(default=0),
        ),
    ]
